version: "3.8"

services:
  api:
    container_name: api
    build: ./api
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./api:/usr/src/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./client:/usr/src/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: accelerisk_db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
    ports:
      - "8080:80"

volumes:
  db-data:
